### PR TITLE
reworked to split files + new QX7 version

### PR DESCRIPTION
**Pull request by raphaelcoeffic**
Split BFSetup.lua into:
 - common/msp_sp.lua
 - common/ui.lua
 - X9.lua

Added X7.lua to support the new Taranis QX7.

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
Obsoletes #7

**Comment by Alveran81** [comment]
Very nice work. On Taranis X7 adjust Knob is not working. So I can not modify settings when Lua Script is running.

**Comment by raphaelcoeffic** [comment]
@Alveran81 did you start the script as a Telemetry script, or as from the SD card explorer? Also, which OpenTX release are you using?

**Comment by Alveran81** [comment]
I'am using Version N362. Its startet as Telemetry Script. Settings Page 13/13 in Menu. Starting Lua Script with long Press Page.

**Comment by raphaelcoeffic** [comment]
@Alveran81 ok, there is still a bug on OPenTX which has been fixed in between. Wait for RC11, and execute from the SD explorer in between.

**Comment by raphaelcoeffic** [comment]
Thought it was written in the release notes for v0.1....

**Comment by Alveran81** [comment]
Executed with SD Explorer is working. Thanks

**Pull request merged**
