### PR TITLE
add support for Jumper t16

### PR DESCRIPTION
**Pull request by andyddd**
add support for Jumper t16

### CODE REVIEW

**Comment by lucdesorel** [comment]
my t16 have the firmware 2.3 and i cant bind correctly to my optima receiver.  big big lag from 3 to 5 second....  did try to change firware in receiver, but noting work...  but with my frsky d8r-II everything work perfect..  can you help me please...

**Comment by mikeller** [comment]
@lucdesorel: This repository is for the Betaflight TX lua scripts only, and not for OpenTX. Please open an issue for your problem in https://github.com/opentx/opentx/issues.

**Comment by tiaanv** [comment]
Jumper T16 Pro
BF script 1.4.1
OpenTX 2.3.2N27 nightly build
Multiprotocol module updated to latest with bootloader (FWIW)
the BF.lua script runs fine... can also page through various settings... but nothing has values.
Telemetry works fine.
BF script on my Taranis X7 with exact same quad worked fine... 

I'm guessing this is not ready for primetime yet.  Not sure if anyone has got it working yet.

**Comment by tenten8401** [comment]
@tiaanv I have the same issue, multi-module also updated to latest with the bootloader. Just no values at all.

**Comment by tiaanv** [comment]
@tenten8401. This is an OpenTX issue, related to the multiprotocol module, more than the T16.  It is known, and a fix is in the pipeline.  No ETA yet, but I'm sure with the Jumper T16 relying heavily on it, it should be soon enough.
See here:
https://github.com/opentx/opentx/issues/7005#issuecomment-546360511

**Pull request merged**
