### PR TITLE
changed layout of PIDs and Rates to make it look more like as in beta…

### PR DESCRIPTION
**Pull request by JR63**
Hi,

I adapted the script for X7 to make it looking a little bit more like the original betaflight layout.

The small change in ui.lua will only affect the X7 and X9, it is needed for smaller size characters.

So we have Roll, Pitch, Yaw as rows on both pages.

The P, I, D values come as columns on the PIDs Page.

bf_lua_simu_pids

The RC Rate, Super Rate, RC Expo values come in a smaller type and as columns  in the same order as in betaflight on the Rates Page.

bf_lua_simu_rates

The VTX page is unchanged.

bf_lua_simu_vtx

I tested it in companion and on a real Taranis Q X7 with SPRacingF3 running betaflight and FrSky X4RSB.

Betaflight / SPRACINGF3 3.1.5 Feb 7 2017 / 22:30:44 (4646f9d)

Bye
JR

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@JR63 Looks really cool! I'll give it a shot ASAP, and merge if everything is ok.

**Comment by JR63** [comment]
@raphaelcoeffic That sounds good. Thanks.

**Comment by JR63** [comment]
@raphaelcoeffic 
By the way: I can do the same for X9 and maybe for Horus.
But I can only test with companion because I only own a real X7.

**Comment by raphaelcoeffic** [comment]
> On 21 Feb 2017, at 17:00, JR63 <notifications@github.com> wrote:
> 
> @raphaelcoeffic <https://github.com/raphaelcoeffic>
> By the way: I can do the same for X9 and maybe for Horus.
> But I can only test with companion because I only own a real X7.
> 
Sounds good to me! I can test on X9 and I know somebody for the Horus. In fact, we could even have some bitmaps for these targets ;-)

**Comment by JR63** [comment]
@raphaelcoeffic 
Ok, I did it for X9 and Horus and checked both with companion.
Because all 3 uses the same indexing (by variable i) I'm quite shure it will work for X7, X9 and Horus because I tested it with the X7.

**Comment by JR63** [comment]
And here are the screen shots for X9 and Horus:

bf_lua_simu_x9_pids

bf_lua_simu_x9_rates

bf_lua_simu_horus_pids

bf_lua_simu_horus_rates

**Comment by si618** [comment]
Thanks @JR63, I've closed my PR for the X9 change.

**Comment by ronerone** [comment]
displays correctly here, BF3.1.5, open tx 2.2 RC10 with last released script modified to reflect your changes.

**Comment by JR63** [comment]
Many thanks for your testing.

**Comment by si618** [comment]
+1 for @JR63 changes, tested pid and rate pages on my x9+; working well and looking good!

**Comment by JR63** [comment]
Cool, thanks to you also.

**Comment by SoulPictures** [comment]
Seems to work fine on a physical Horus with RC10, no visible glitches

**Comment by JR63** [comment]
Cool, thanks for testing on Horus.

**Comment by raphaelcoeffic** [comment]
@JR63 Thx a lot for the work! I think we're good to merge now.

**Comment by JR63** [comment]
That sounds very good. Many thanks to all.

**Comment by raphaelcoeffic** [comment]
New release has been pushed (v0.3) to make the changes available.

**Comment by ronerone** [comment]
mmh! had a weird issue in iu.lua while navigating the screen pages. an error on line 238 if i remember well.
I restarted the taranis and it was ok.
I'm sorry i couldn't write somewhere the exact line and message, but it was probably in function drawMenu.
I'll try to take a picture if it appears again.
For the time being, i keep the 0.2 version i modified which i think should be the same as v0.3.

**Comment by JR63** [comment]
Hi,
This pull request did'nt changed the vtx pages.
So, if your issue can be reproduced with the newest code, I suggest to open an issue on the main project page, thanks.

**Comment by ronerone** [comment]
hi JR63? no problem. i was suspecting an issue due to the fact i had manually added the code to 0.2 version, which i may have uncorrectly made. I'll check later if i reproduce.
Thanks to all for your improvements!

**Pull request merged**
