### PR TITLE
Hide OSD (SD) settings

### PR DESCRIPTION
**Pull request by atomgomba**
Follow up PR on #495. Please merge #495 first, because it contains the parent commit.

### CODE REVIEW

**Comment by atomgomba** [comment]
It looks like on some boards getting the OSD config may take a lot of time over CRSF

**Comment by TheIsotopes** [comment]
Tested and everything seems to work.

Imo a rebase is still missing here.

**Comment by atomgomba** [comment]
> Tested and everything seems to work.
> 
> Imo a rebase is still missing here.

Seemingly it doesn't *always* work for me. I tested using 4 different quads. My radio is Tango 2 with FreedomTX, what's your radio? I'm starting to feel like I'm gonna need more hardware for testing. I can get a Micro TX for my Taranis X9D+ to have one more test device.

**Comment by TheIsotopes** [comment]
I use the RM Zorro with EdgeTX for FrSky and Ghost receivers.

**Comment by atomgomba** [comment]
With [#13333](https://github.com/betaflight/betaflight/pull/13333) we're slowly getting to the point where firing a single MSP request to get the supported options will be enough. Waiting for multiple responses takes inconveniently lot amount of time, I'm planning to put this PR on hold until we have a better way to check build options.

**Comment by klutvott123** [comment]
> With [#13333](https://github.com/betaflight/betaflight/pull/13333) we're slowly getting to the point where firing a single MSP request to get the supported options will be enough. Waiting for multiple responses takes inconveniently lot amount of time, I'm planning to put this PR on hold until we have a better way to check build options.

This is probably the best solution. I think we should put everything else on hold just to avoid ending up with multiple solutions and compatibility issues. We have three solutions to this right now, and we should pick just one. 
I'm not sure which protocol you're testing this with, but the worst case scenario is FPORT as it's super slow.

**Comment by atomgomba** [comment]
> > With [#13333](https://github.com/betaflight/betaflight/pull/13333) we're slowly getting to the point where firing a single MSP request to get the supported options will be enough. Waiting for multiple responses takes inconveniently lot amount of time, I'm planning to put this PR on hold until we have a better way to check build options.
> 
> This is probably the best solution. I think we should put everything else on hold just to avoid ending up with multiple solutions and compatibility issues. We have three solutions to this right now, and we should pick just one. I'm not sure which protocol you're testing this with, but the worst case scenario is FPORT as it's super slow.

Currently I've only tested on CRSF, but on two "different" platforms, FreedomTX and EdgeTX. I happen to own an X9D+ and FrSky receivers so with a bit of soldering I can test FPORT too. Thanks for the heads up!

**Comment by atomgomba** [comment]
New plan is to have a dedicated MSP command for clients using OTA transmission, please see [#13344](https://github.com/betaflight/betaflight/pull/13344)

**Comment by atomgomba** [comment]
This is not stale, just waiting for [#13333](https://github.com/betaflight/betaflight/pull/13333) to be merged. I presume it's most likely to happen after 4.5 release.

**Comment by haslinghuis** [comment]
@TheIsotopes pls test again :) (needs latest dev firmware)

**Comment by atomgomba** [comment]
> @TheIsotopes pls test again :) (needs latest dev firmware)

well, it's only needed to test the happy path. by design the menu will load either way ;) btw I also tested this, but more tests the better. testing against MSP version <= 1.46 is a real scenario as well. so far I haven't tested against BF 4.4, but I'm planning to do so in the weekend

**Comment by TheIsotopes** [comment]
@atomgomba @haslinghuis
tested on my Zorro, everything seems to be working correctly for me. 👍

**Review by haslinghuis — APPROVED** [review]

**Comment by atomgomba** [comment]
tested on 4.4.3, works as expected

**Pull request merged**
