### PR TITLE
Add BF Scripts to OpenTX 2.3.x Tools screen

### PR DESCRIPTION
**Pull request by frozenskys**
Adds the betaflight scripts to the OpenTx Tools screen introduced in 2.3. Needs the virtual event changes merged from #250 first

This was split from #252

### CODE REVIEW

**Comment by raphaelcoeffic** [comment]
@frozenskys sorry for the disagreement, but could you please rebase on top of the current `virtual-events` branch? I rebased /squashed the commits with my back-and-forth. Please note that when you use the correct base branch, it makes it clearer on which PR yours is based.

**Comment by raphaelcoeffic** [comment]
@mikeller @frozenskys I don't know what you think, but I'd say we should even remove `/BF/bf.lua` in favour of this one. There is no point in having the "standalone" startup script, as all the radios have the tools menu now, and it is really much better than going to the SD manager.

**Comment by mikeller** [comment]
@raphaelcoeffic:

> I don't know what you think, but I'd say we should even remove /BF/bf.lua in favour of this one.

Yes that makes sense. We could add an empty file named `/BF/use_tools_menu_instead_of_this.txt` for a couple of versions to help users make the switch. :wink:

**Comment by frozenskys** [comment]
Help, not sure my rebase has worked :( any advice appreciated.

**Comment by raphaelcoeffic** [comment]
@frozenskys in case you invite me, I can rebase it for you and push it to your branch.

**Comment by frozenskys** [comment]
Invited thanks! - and be careful, it's a mess in there - git is not my friend... yet!

**Comment by raphaelcoeffic** [comment]
@frozenskys done!

@mikeller should we just only have the text file extra? I thought removing `/BF/bf.lua` as well.

**Comment by mikeller** [comment]
@raphaelcoeffic: Yes, the idea was to remove `/BF/bf.lua` and add the text file, so when a user goes there in the file explorer when they want to start the script they see the text file and know what to do.

**Pull request merged**
