### PR TITLE
VTX memory savings

### PR DESCRIPTION
**Pull request by klutvott123**
Have vtx_defaults.lua/modelname.lua return their tables to vtx.lua instead of using globals. This prevents the tables that are specific only to vtx.lua to be loaded all the time. Should save between 1 and 2k of memory when the vtx page is not selected.

### CODE REVIEW

**Comment by klutvott123** [comment]
@frozenskys Done!

**Comment by frozenskys** [comment]
@klutvott123 looks good - did you see @mikeller's comments on https://github.com/betaflight/betaflight-configurator/pull/1822 ? What does everyone think?

**Comment by klutvott123** [comment]
@frozenskys I just moved ``deviceTable`` and ``pitModeTable`` to vtx.lua. We can always change it later without making more changes to the configurator.

**Comment by frozenskys** [comment]
@klutvott123 looks spot on.. Thanks for your help on this...

**Pull request merged**
