### PR TITLE
Virtual events

### PR DESCRIPTION
**Pull request by mikeller**
Merge #253 and #254 into master.

### CODE REVIEW

**Comment by RipperDrone** [comment]
@raphaelcoeffic @mikeller It seems the Virtual Events / OTX mismatch confusion is going on: Downloaded lua 1.4.0, overwrote with https://github.com/betaflight/betaflight-tx-lua-scripts/tree/virtual-events, then tested on Taranis X9D+ --> different result now: When decrementing e.g. a PID value, it stays decremented for like 1-2 secs, then changes back to what it was before. As if the script was re-reading the number from Taranis without taking the change into consideration. Plus: Sometimes when hitting ENTER to edit one parameter, the edit field does not flash  / get enabled. When switching back and forth btw 1st lua page (display) and 2nd lua page (edit BF parms), it becomes editable...

**Comment by mikeller** [comment]
@RipperDrone: Not sure why you are using a hodgepodge of different versions and not just the released version that is working.

**Comment by RipperDrone** [comment]
Released version is not working. I haven'T been able to identify any version working with OTX 2.3.1 on Taranis X9D+. Which one is expected to work ok? Lua 1.4 is not... :-/

**Comment by mikeller** [comment]
@RipperDrone: 1.4.0 is working fine for me with OpenTX 2.3.1 on X9D+. What does not work for you?

**Comment by RipperDrone** [comment]
Same behavior like described before: 

- BF4.1RC6, OTX 2.3.1, Lua 1.4.0 --> When changing values in lua script (e.g. decrementing Roll P), the decremented value stays for some time, then it swaps back into previous / unchanged value.

**Comment by mikeller** [comment]
@RipperDrone: This works fine for me. Are you starting the script as a telemetry page? If so, can you try clearing / re-formatting the SD card in your X9D+ and reinstalling the OpenTX contents and then the Betaflight TX lua scripts? There's an off chance that there are some leftovers from past versions.

**Comment by RipperDrone** [comment]
yes, starting it as a telemetry page (page 2, when page 1 is just displaying a selected telemetry values matrix). Will try...

**Comment by RipperDrone** [comment]
@mikeller test done:

- formatted SD on Taranis X9D+ (2013)
- flashed 2.3.1 OTX firmware from OTX Companion
- dumped OTX 2.3.1 SD content on SD
- copied Lua 1.4.0 files to SD
- long press PAGE for telemetry display page (configured as page 1)
- short press PAGE for lua parms edit pages (configured as page 2)
- press ENTER to edit Roll P
- decrement Roll P and wait --> it jumps back to unchanged value

Still doesn't work on my setup.

**Comment by mikeller** [comment]
@RipperDrone: That's weird - exactly the same behaviour works fine for me, and my setup is the same as yours. Maybe @raphaelcoeffic can reproduce the problem?

**Comment by RipperDrone** [comment]
@mikeller - I'm baffled. Can repeat on with any lua parameter page, with any value - always first time editing the page only. 

There has been a working version in between the PRs addressing virtual events, I think it was @raphaelcoeffic 's reference to PR#250 or #253. The links given there do no longer work, pbly due to his local branches / content having been merged and delted in the meantime. Cannot reproduce the working combination anymore. This is the reason why I was trying to mix OTX2.3.1 with some earlier stage of master... no luck, same as with Lua 1.4.0...

**Comment by RipperDrone** [comment]
@mikeller @raphaelcoeffic it was this .zip file which made it work on my setup (but this zip file is empty now...)
image

**Comment by raphaelcoeffic** [comment]
I have the feeling somethings strange is going on. Let’s imagine for one second that the page is loaded twice. And as it takes so long, and you edit some field while it is doing the second loading in the background.

**Comment by raphaelcoeffic** [comment]
Ok, then we might have to check what happened in between.

**Comment by RipperDrone** [comment]
@raphaelcoeffic Jeez, believing you nailed it: When waiting for 10 secs after loading any parameters page and only then proceeding to change values, IT WORKS AS SUPPOSED - no auto-readjusting of the values changed anymore!

This seems to be in line with the general feedback that parameter page loading has slowed down a lot, it sometimes takes 6 secs to load a page now. Has been lots faster before. Plus, the annoying 'Retrying...' message has come back when trying to save (every single time!), which the dev team almost had tricked out by implementing some watchdog timing (I remember it cannot be made bullet proof because there is no bidir acknowledging of commands received...).

**Comment by RipperDrone** [comment]
tried #259 doesn't fix it - though it maybe fixes the occasional non-react on 1st start of the lua telemetry script.

**Comment by frozenskys** [comment]
#259 was just meant to fix the non-reaction to events on first load of the telemetry script. 

I've run both on my X7 (on OTX 2.3.1) and don't have any issues with values not changing or saving, although I have currently only tested on FrSky telemetry and I do have the telemetry mod done.

**Comment by raphaelcoeffic** [comment]
@mikeller @RipperDrone I have made a PR for testing some fixes I've just made. These changes are base directly on 1.4.0 to make it simple. @frozenskys once We have 1.4.0 fixed, let's tackle your fixes against master.

Here is the PR: https://github.com/betaflight/betaflight-tx-lua-scripts/pull/260

**Comment by RipperDrone** [comment]
Yep, fixes it perfectly! Good work! :-)

PS: Reading values from FC over telemetry is still very slow, some pages take 6 secs+ to populate. MAybe it's purpose design to NOT make telemetry packets with so many sensors swamp the radio transmission pipeline...

**Comment by mikeller** [comment]
@RipperDrone: Re the slowness, what RX type / protocol / firmware version are you using? Some firmware versions have got issues with encoding, which could lead to errors / retransmissions. Can you try updating your RX firmware to the latest version? Also, I don't know if the built-in TX in the X9D+ had similar issues in older versions, but an update to the latest firmware version can't hurt there either.

**Comment by RipperDrone** [comment]
@mikeller thanks for this hint. The quad I tested with for last couple of weeks has a CRSF micro TX/Nano RX combo, latest firmware installed over TBS AgentX. Wired up with TX/RX, CRSF protocol on Taranis and Nano.

**Comment by RipperDrone** [comment]
maybe it's relted to https://github.com/betaflight/betaflight/issues/6894

**Comment by mikeller** [comment]
I don't have much practical experience with CRSF, but the 50 Hz mode has got a limited bandwidth, so I would assume that whenever it goes into this mode the bandwidth available for telemetry will be minimal.

**Comment by Dyrt-Nasti** [comment]
does anyone know how to get around this screen, everything is setup and ready but when i hold the 'PAGE' key this pops up

**Comment by klutvott123** [comment]
The telemetry script is removed from 1.5.0. It has been replaced by "Betaflight setup" which can be found in the TOOLS menu

**Comment by Dyrt-Nasti** [comment]
once i enter the Betaflight setup tab in my QX7 it just initializes and nothing else, anybody got advice on how to get past

**Comment by klutvott123** [comment]
@Dyrt-Nasti Power on your quad. The script is waiting for a connection

**Comment by Dyrt-Nasti** [comment]
powered on the quad, have connection and telem. is working but still cant get past initializing

**Comment by klutvott123** [comment]
@Dyrt-Nasti Strange. Could you open an issue, please? And provide information about your hardware/firmware

**Comment by Dyrt-Nasti** [comment]
posted the issue, if you got questions ask

**Pull request merged**
